"""Capture real API responses and write them where the frontend can import them.

    python scripts/snapshot_contract.py

Why this exists
---------------
`ui/lib/mocks.js` was hand-written to match the backend contract. Hand-written
mocks drift the moment a field is added, and the drift is invisible until
integration - which is the worst possible time to find it.

This runs the real app in MOCK_MODE, exercises every endpoint, and writes the
actual responses to ui/lib/contract-snapshot.json. The frontend imports that
file, so the mocks cannot disagree with the backend by construction.

Re-run it after any schema change. Commit the output.
"""
from __future__ import annotations

import io
import json
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ["MOCK_MODE"] = "true"

# Keep the snapshot out of the real data directory.
SNAPSHOT_DATA = ROOT / "data" / ".snapshot"
SNAPSHOT_DATA.mkdir(parents=True, exist_ok=True)
os.environ["DATA_DIR"] = str(SNAPSHOT_DATA)

from fastapi.testclient import TestClient  # noqa: E402

from api.main import app  # noqa: E402
from api.models.schemas import DocumentKind, EventReport, EventType  # noqa: E402
from api.rules.engine import IST, evaluate  # noqa: E402
from api.rules.loader import load_rules  # noqa: E402
from api.services import cases as case_store  # noqa: E402
from api.services import profile as profile_store  # noqa: E402

OUT = ROOT / "ui" / "lib" / "contract-snapshot.json"

client = TestClient(app)
rules = load_rules()
now = datetime.now(IST)


def _reset() -> None:
    for name in ("cases.json", "profile.json"):
        path = SNAPSHOT_DATA / name
        if path.exists():
            path.unlink()


def _seed_case(event: EventReport, rule_id: str):
    claim = next((c for c in evaluate(event, rules) if c.rule_id == rule_id), None)
    if claim is None:
        raise RuntimeError(f"Seeding failed: {rule_id} did not trigger")
    return case_store.create_case(event, claim)


def build() -> dict:
    _reset()
    snapshot: dict = {
        "_generated": now.isoformat(),
        "_note": "Generated by scripts/snapshot_contract.py. Do not hand-edit.",
    }

    # --- every case status the UI must render -------------------------------
    # open: crop loss 24h ago, 48h left
    _seed_case(
        EventReport(
            event_type=EventType.HAILSTORM,
            event_datetime=now - timedelta(hours=24),
            crop="cotton",
            area_acres=1.5,
            has_pmfby_policy=True,
            district="Ballari",
        ),
        "PMFBY_LOCALISED",
    )
    # closing_soon: 66h ago, ~6h left
    _seed_case(
        EventReport(
            event_type=EventType.HAILSTORM,
            event_datetime=now - timedelta(hours=66),
            crop="maize",
            area_acres=0.8,
            has_pmfby_policy=True,
        ),
        "PMFBY_LOCALISED",
    )
    # expired: 100h ago
    _seed_case(
        EventReport(
            event_type=EventType.HAILSTORM,
            event_datetime=now - timedelta(hours=100),
            crop="groundnut",
            has_pmfby_policy=True,
        ),
        "PMFBY_LOCALISED",
    )
    # the second vertical
    _seed_case(
        EventReport(
            event_type=EventType.UNAUTHORISED_TRANSACTION,
            bank_communication_datetime=now - timedelta(hours=20),
            has_bank_account=True,
            transaction_amount=18400.0,
        ),
        "RBI_UNAUTH_TXN",
    )

    snapshot["GET /api/cases"] = client.get("/api/cases").json()

    first = snapshot["GET /api/cases"][0]["case_id"]
    snapshot["GET /api/cases/{id}"] = client.get(f"/api/cases/{first}").json()

    # A case with a ticked step and an attached photo, so the UI can render the
    # "in progress" state without guessing its shape.
    steps = snapshot["GET /api/cases/{id}"]["steps"]
    client.patch(f"/api/cases/{first}/steps/{steps[0]['step_id']}", json={"done": True})
    client.post(
        f"/api/cases/{first}/photo",
        files={"image": ("shot.jpg", io.BytesIO(b"fakejpeg"), "image/jpeg")},
        data={
            "lat": "15.1394",
            "lon": "76.9214",
            "accuracy_m": "8.0",
            "step_id": steps[1]["step_id"],
        },
    )
    snapshot["GET /api/cases/{id} (in progress)"] = client.get(
        f"/api/cases/{first}"
    ).json()

    # A case with EVERY step ticked. Without this, mock mode can never reach the
    # document screen - which matters because mock mode IS the fallback if
    # inference dies before the demo.
    done_case = _seed_case(
        EventReport(
            event_type=EventType.HAILSTORM,
            event_datetime=now - timedelta(hours=12),
            crop="sunflower",
            area_acres=2.2,
            has_pmfby_policy=True,
            district="Ballari",
        ),
        "PMFBY_LOCALISED",
    )
    for step in client.get(f"/api/cases/{done_case.case_id}").json()["steps"]:
        client.patch(
            f"/api/cases/{done_case.case_id}/steps/{step['step_id']}", json={"done": True}
        )
    snapshot["GET /api/cases/{id} (all steps done)"] = client.get(
        f"/api/cases/{done_case.case_id}"
    ).json()

    # English reads of a stored case, for the language toggle.
    snapshot["GET /api/cases?lang=en"] = client.get("/api/cases?lang=en").json()

    # --- intake, both languages ---------------------------------------------
    audio = {"audio": ("clip.webm", io.BytesIO(b"fake"), "audio/webm")}
    snapshot["POST /api/intake (kn)"] = client.post("/api/intake", files=audio).json()
    snapshot["POST /api/intake (en)"] = client.post(
        "/api/intake",
        files={"audio": ("clip.webm", io.BytesIO(b"fake"), "audio/webm")},
        data={"lang": "en"},
    ).json()

    # --- onboarding ----------------------------------------------------------
    profile_store.reset_profile()
    snapshot["GET /api/profile (first run)"] = client.get("/api/profile").json()
    snapshot["GET /api/profile/completeness (first run)"] = client.get(
        "/api/profile/completeness"
    ).json()

    for kind in DocumentKind:
        snapshot[f"POST /api/profile/scan ({kind.value})"] = client.post(
            "/api/profile/scan",
            files={"image": ("doc.jpg", io.BytesIO(b"fakejpeg"), "image/jpeg")},
            data={"kind": kind.value},
        ).json()

    snapshot["POST /api/profile/confirm"] = client.post(
        "/api/profile/confirm",
        data={
            "kind": "pmfby_certificate",
            "fields": json.dumps(
                {
                    "pmfby_policy_number": "PMFBY/KA/2026/8841",
                    "crop": "Cotton",
                    "land_acres": "1.5",
                    "survey_numbers": "142/3",
                }
            ),
        },
    ).json()
    snapshot["GET /api/profile/completeness (after scan)"] = client.get(
        "/api/profile/completeness"
    ).json()

    snapshot["GET /health"] = client.get("/health").json()

    # --- error shapes the UI has to handle -----------------------------------
    missing = client.get("/api/cases/c_does_not_exist")
    snapshot["GET /api/cases/{id} (404)"] = {
        "status": missing.status_code,
        "body": missing.json(),
    }

    return snapshot


def main() -> None:
    snapshot = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(snapshot, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    _reset()
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"{len(snapshot) - 2} endpoint responses captured:\n")
    for key in snapshot:
        if not key.startswith("_"):
            print(f"  {key}")

    statuses = {c["claim"]["status"] for c in snapshot["GET /api/cases"]}
    print(f"\nCase statuses covered: {sorted(statuses)}")
    missing_statuses = {"open", "closing_soon", "expired"} - statuses
    if missing_statuses:
        print(f"WARNING: no example of {sorted(missing_statuses)}")


if __name__ == "__main__":
    main()